title: Gonto â€” An engineering approach to marketing
short_title: Gonto
description: "Gonto is a software engineer that now works on Marketing. He found a way to combine my 2 passions and apply my engineering thinking model to Marketing"
source:      ./
destination: ./_site
exclude: [".sass-cache", "node_modules", "bower_components", "bower.json", "package.json", "gruntfile.js", "readme.md", "_assets"]
encoding: utf-8
paginate: 9
disqus_shortname: gontosblog
reading_time:     true
words_per_minute: 200
email: martin@gon.to

url: "https://gon.to"

paginate_path: "thoughts/page:num"

excerpt_separator: <!--more-->
gems: [jekyll-paginate]
owner:
  name: Martin Gontovnikas
  email: martin@gon.to
  twitter: mgonto

google_analytics: UA-48082910-1


timezone:    America/New_York
future:      true
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-archives


jekyll-archives:
  enabled:
    - tags
  layout: 'tags'
  permalinks:
    tag: '/tag/:name/'


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: pretty

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post

# Format titles with titlecase?
titlecase: true
